return {
  ["lavaburst"] = {
     usedefaultexplosions = false,
      Spawner = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = [[1 i3]],
      ground             = true,
      water              = true,
      unit               = 0,
      properties = {
        delay              = [[2 i7]],
        explosiongenerator = [[custom:lava_explo]],
        pos                = [[0, 0, 0]],
      },
    },
     Spawner1 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 2,
      ground             = true,
      water              = true,
      unit               = 0,
      properties = {
        delay              = [[2 i13]],
        explosiongenerator = [[custom:lava_explo1]],
        pos                = [[0, 0, 0]],
      },
    },
      Spawner2 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 2,
      ground             = true,
      water              = true,
      unit               = 0,
      properties = {
        delay              = [[2 r10]],
        explosiongenerator = [[custom:lava_explo2]],
        pos                = [[0, 0, 0]],
      },
    },
         Spawner3 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 3,
      ground             = true,
      water              = true,
      unit               = 0,
      properties = {
        delay              = [[2 i9]],
        explosiongenerator = [[custom:lava_explo_middle]],
        pos                = [[0, 0, 0]],
      },
    },
      Spawner4= {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 3,
      ground             = true,
      water              = true,
      unit               = 0,
      properties = {
        delay              = [[2 r7]],
        explosiongenerator = [[custom:lava_explo3]],
        pos                = [[0, 0, 0]],
      },
    },
},
 
   ["lava_explo"] = {
    spark = {
       air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,--26
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.98,
        alwaysvisible      = true,
        colormap           = [[0.8 0.8 0.2 1   1 0.4 0.2 1        0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = [[0 r-360 r360]],
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.2, 0]],
        numparticles       = 20,
        particlelife       = 50,
        particlelifespread = 35,
        particlesize       = [[1 r10]],
        particlesizespread = 12,
        particlespeed      = 4,
        particlespeedspread = 3,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[map_debris2]],
      },
    },
  },
   ["lava_explo1"] = {
    spark = {
       air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,--26
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        alwaysvisible      = true,
        colormap           = [[0.8 0.8 0.2 1   1 0.3 0.1 1        0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = [[0 r-360 r360]],
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 20,
        particlelife       = 50,
        particlelifespread = 35,
        particlesize       = [[1 r10]],
        particlesizespread = 12,
        particlespeed      = 4,
        particlespeedspread = 3,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[map_debris2]],
      },
    },
  },
     ["lava_explo2"] = {
    spark = {
       air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,--26
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.94,
        alwaysvisible      = true,
        colormap           = [[0.8 0.8 0.2 1   1 0.4 0.1 1        0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = [[0 r-360 r360]],
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.2, 0]],
        numparticles       = 20,
        particlelife       = 50,
        particlelifespread = 35,
        particlesize       = [[20 r25]],
        particlesizespread = 12,
        particlespeed      = 4,
        particlespeedspread = 3,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[map_debris2]],
      },
    },
  },
     ["lava_explo3"] = {
    spark = {
       air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,--26
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.94,
        alwaysvisible      = true,
        colormap           = [[0.8 0.8 0.2 1   1 0.4 0.1 1        0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = [[0 r-360 r360]],
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.2, 0]],
        numparticles       = 1,
        particlelife       = 50,
        particlelifespread = 35,
        particlesize       = [[30 r25]],
        particlesizespread = 12,
        particlespeed      = 4,
        particlespeedspread = 3,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[debris]],
      },
    },
  },
    ["lava_explo_middle"] = {
    spark = {
        air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0.6 0.2 0 0.1    0.4 0.2 0 0.1  0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 25,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 40,
        particlelife       = 28.5,
        particlelifespread = 5,
        particlesize       = 0.25,
        particlesizespread = 2,
        particlespeed      = 2,
        particlespeedspread = 19,
        pos                = [[0, 2, 0]],
        sizegrowth         = 2,
        sizemod            = 1.0,
        texture            = [[map_dirtplosion2]],
      },
    },
  },
}